### ISSUE TITLE
Ogg decoding on other Haxe targets than flash?

### ISSUE THREAD

**Issue by cambiata** [TuduraoJin/VorbisAS#1]
Cool!

Is the ogg decoding tied to flash, or would it be possible to use this solution for decoding ogg on other platforms? (Not talking about playback here, just ogg to raw sample data - wav or other).

Jonas

**Comment by TuduraoJin** [comment]
yes. pherhaps.
I found decoding process from this repository.  using this source to VorbisAS.
[shohei909/haxe_stb_ogg_sound
](https://github.com/shohei909/haxe_stb_ogg_sound)

please check the repository's sample directory.
Ogg2WavFlash.hx is an sample code, encoding ogg to wav for flash.
Ogg2WavSys.hx is encoding ogg to wav for other platform. C#, neko and Java.
( but , I have never compile and try the sample. just reading. sorry.)

I hope this will help.
thank you.

**Comment by cambiata** [comment]
Thanx for info! Keep up!
